// client/src/components/members.vue
<template>
  <div class="members">
    <div class="members-container">
      <ul class="members-list">
        <li v-if="member">
          <div :class="[{ host: member.id === host }, 'self', 'member']">
            <neko-avatar class="avatar" :seed="member.displayname" :size="50" />
          </div>
        </li>
        <template v-for="(member, index) in members">
          <li
            v-if="member.id !== id && member.connected"
            :key="index"
            v-tooltip="{ content: member.displayname, placement: 'bottom', offset: -15, boundariesElement: 'body' }"
          >
            <div
              :class="[{ host: member.id === host, admin: member.admin }, 'member']"
              @contextmenu.stop.prevent="onContext($event, { member })"
            >
              <neko-avatar class="avatar" :seed="member.displayname" :size="50" />
            </div>
          </li>
        </template>
      </ul>
    </div>
    <neko-context ref="context" />
  </div>
</template>

<style lang="scss" scoped>
  .members {
    flex: 1;
    overflow-x: scroll;
    overflow-y: hidden;
    padding-bottom: 14px;
    scrollbar-width: thin;
    scrollbar-color: $background-secondary $background-tertiary;
    min-height: 60px;
    display: flex;

    &::-webkit-scrollbar {
      height: 4px;
    }

    &::-webkit-scrollbar-track {
      background-color: $background-tertiary;
    }

    &::-webkit-scrollbar-thumb {
      background-color: $background-secondary;
      border-radius: 4px;
    }

    &::-webkit-scrollbar-thumb:hover {
      background-color: $background-primary;
    }

    .members-container {
      display: block;
      clear: both;
      padding: 0 20px;
      margin: 0 auto;

      .members-list {
        white-space: nowrap;
        clear: both;

        li {
          display: inline-block;

          .member {
            position: relative;
            display: block;
            width: 50px;
            height: 50px;
            margin: 10px 5px 0 5px;

            &.self {
              &::before {
                font-family: 'Font Awesome 6 Free';
                font-weight: 900;
                content: '\f2bd';
                background: $background-floating;
                color: $style-primary;
                position: absolute;
                width: 15px;
                height: 15px;
                line-height: 15px;
                font-size: 20px;
                text-align: center;
                margin-top: -2px;
                margin-left: 40px;
                border-radius: 50%;
              }
            }

            &.admin {
              &::before {
                display: block;
                font-family: 'Font Awesome 6 Free';
                font-weight: 900;
                content: '\f3ed';
                color: $style-primary;
                background: transparent;
                position: absolute;
                width: 14px;
                height: 14px;
                font-size: 14px;
                text-align: center;
                margin-top: -2px;
                margin-left: 44px;
              }
            }

            &.host::after {
              display: block;
              font-family: 'Font Awesome 6 Free';
              font-weight: 900;
              content: '\f521';
              background: $style-primary;
              color: $background-floating;
              position: absolute;
              width: 20px;
              height: 20px;
              line-height: 20px;
              font-size: 10px;
              text-align: center;
              margin-top: 42px;
              margin-left: -18px;
              border-radius: 50%;
            }

            .avatar {
              border-radius: 50%;
              overflow: hidden;
              width: 100%;
            }
          }

          &:nth-child(2) {
            margin-left: 20px;

            &::before {
              position: absolute;
              content: ' ';
              height: 45px;
              width: 2px;
              background: $background-secondary;
              margin-top: 13px;
              margin-left: -9px;
            }
          }
        }
      }
    }
  }
</style>

<script lang="ts">
  import { Component, Ref, Vue } from 'vue-property-decorator'

  import Content from './context.vue'
  import Avatar from './avatar.vue'

  @Component({
    name: 'neko-members',
    components: {
      'neko-context': Content,
      'neko-avatar': Avatar,
    },
  })
  export default class extends Vue {
    @Ref('context') readonly _context!: any

    get id() {
      return this.$accessor.user.id
    }

    get host() {
      return this.$accessor.remote.id
    }

    get member() {
      return this.$accessor.user.member
    }

    get members() {
      return this.$accessor.user.members
    }

    onContext(event: MouseEvent, data: any) {
      this._context.open(event, data)
    }
  }
</script>

// client/src/features/members/Members.tsx
import { useStore } from 'zustand'
import { useShallow } from 'zustand/react/shallow'
import { selectSession } from '@m1k1o/neko'
import { cn } from '@/lib/utils'
import { openMenu } from '@/state/actions'
import { app } from '@/state/app'
import { client } from '@/state/client'
import { Avatar } from '@/components/Avatar'

// keyboard equivalent of right-click: the Menu key or Shift+F10 on a focused member
const menuKey = (e: React.KeyboardEvent, id: string) => {
  if (e.key !== 'ContextMenu' && !(e.shiftKey && e.key === 'F10')) return
  e.preventDefault()
  e.stopPropagation()
  const r = (e.currentTarget as HTMLElement).getBoundingClientRect()
  if (id !== client.state.session_id) app.setState({ menu: { x: r.left, y: r.bottom, id } })
}

const member = 'relative mt-2.5 mr-[5px] ml-[5px] block h-[50px] w-[50px]'
// the badges on an avatar: you (a user icon), an admin (a shield), the host (a crown)
const self =
  'fas fa-user-circle absolute mt-[-2px] ml-10 h-[15px] w-[15px] rounded-full bg-background-floating text-center text-[20px] leading-[15px] text-style-primary'
const admin = 'fas fa-shield-alt absolute mt-[-2px] ml-11 block h-3.5 w-3.5 text-center text-[14px] text-style-primary'
const host =
  'fas fa-crown absolute mt-[42px] ml-[-18px] block h-5 w-5 rounded-full bg-style-primary text-center text-[10px] leading-5 text-background-floating'
// the others start after a vertical rule
const others =
  'ml-5 before:absolute before:mt-[13px] before:ml-[-9px] before:h-[45px] before:w-0.5 before:bg-background-secondary before:content-[" "]'

export function Members() {
  const { me, hostId, sessions, sessionId } = useStore(
    client.store,
    useShallow((s) => ({
      me: selectSession(s),
      hostId: s.control.host_id,
      sessions: s.sessions,
      sessionId: s.session_id,
    })),
  )
  return (
    <div className="flex min-h-[74px] flex-1 overflow-x-scroll overflow-y-hidden pb-3.5 [scrollbar-color:var(--color-background-secondary)_var(--color-background-tertiary)] [scrollbar-width:thin]">
      <div className="mx-auto block px-5">
        <ul className="whitespace-nowrap">
          {me && (
            <li className="inline-block">
              <div className={member} data-testid="member" data-self data-host={me.id === hostId || undefined}>
                <i className={self} />
                <Avatar seed={me.profile.name} avatar={me.profile.avatar} size={50} />
                {me.id === hostId && <i className={host} />}
              </div>
            </li>
          )}
          {Object.values(sessions)
            .filter((m) => m.id !== sessionId && m.state.is_connected)
            .map((m, i) => (
              <li key={m.id} className={cn('inline-block', i === 0 && others)} title={m.profile.name}>
                <div
                  className={member}
                  data-testid="member"
                  data-host={m.id === hostId || undefined}
                  tabIndex={0}
                  aria-label={m.profile.name}
                  aria-haspopup="menu"
                  onContextMenu={(e) => openMenu(e, m.id)}
                  onKeyDown={(e) => menuKey(e, m.id)}
                >
                  {m.profile.is_admin && <i className={admin} />}
                  <Avatar seed={m.profile.name} avatar={m.profile.avatar} size={50} />
                  {m.id === hostId && <i className={host} />}
                </div>
              </li>
            ))}
        </ul>
      </div>
    </div>
  )
}
