// client/src/components/header.vue
<template>
  <div class="header">
    <a href="https://github.com/m1k1o/neko" title="Github repository" target="_blank" class="neko">
      <img src="@/assets/images/logo.svg" alt="n.eko" />
      <span><b>n</b>.eko</span>
    </a>
    <ul class="menu">
      <li>
        <i
          :class="[{ disabled: !admin }, { 'fa-lock-open': !locked }, { 'fa-lock': locked }, 'fas', 'lock']"
          @click="toggleLock"
          v-tooltip="{
            content: admin
              ? locked
                ? $t('room.unlock')
                : $t('room.lock')
              : locked
              ? $t('room.locked')
              : $t('room.unlocked'),
            placement: 'bottom',
            offset: 5,
            boundariesElement: 'body',
            delay: { show: 300, hide: 100 },
          }"
        />
      </li>
      <li>
        <span v-if="showBadge" class="badge">&bull;</span>
        <i class="fas fa-bars toggle" @click="toggleMenu" />
      </li>
    </ul>
  </div>
</template>

<style lang="scss" scoped>
  .header {
    flex: 1;
    display: flex;
    flex-direction: row;
    align-items: center;

    .neko {
      flex: 1;
      display: flex;
      justify-content: flex-start;
      align-items: center;
      width: 150px;
      margin-left: 20px;
      color: $text-normal;
      text-decoration: none;

      img {
        display: block;
        float: left;
        height: 30px;
        margin-right: 10px;
      }

      span {
        font-size: 30px;
        line-height: 30px;

        b {
          font-weight: 900;
        }
      }
    }

    .menu {
      justify-self: flex-end;
      margin-right: 10px;
      white-space: nowrap;

      li {
        display: inline-block;
        margin-right: 10px;

        i {
          display: block;
          width: 30px;
          height: 30px;
          text-align: center;
          line-height: 32px;
          border-radius: 3px;
          cursor: pointer;
        }

        .disabled {
          cursor: default;
          opacity: 0.8;
        }

        .fa-lock {
          color: rgba($color: $style-error, $alpha: 0.5);
        }

        .toggle {
          background: $background-primary;
        }

        .badge {
          position: absolute;
          background: red;
          font-weight: bold;
          font-size: 1.25em;
          border-radius: 50%;
          width: 20px;
          height: 20px;
          text-align: center;
          line-height: 20px;
          pointer-events: none;

          transform: translate(-50%, -25%) scale(1);
          box-shadow: 0 0 0 0 rgba(0, 0, 0, 1);
          animation: badger-pulse 2s infinite;
        }

        @keyframes badger-pulse {
          0% {
            transform: translate(-50%, -25%) scale(0.85);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.7);
          }

          70% {
            transform: translate(-50%, -25%) scale(1);
            box-shadow: 0 0 0 10px rgba(0, 0, 0, 0);
          }

          100% {
            transform: translate(-50%, -25%) scale(0.85);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
          }
        }
      }
    }
  }
</style>

<script lang="ts">
  import { Component, Ref, Watch, Vue } from 'vue-property-decorator'

  @Component({ name: 'neko-settings' })
  export default class extends Vue {
    get admin() {
      return this.$accessor.user.admin
    }

    get locked() {
      return this.$accessor.locked
    }

    get side() {
      return this.$accessor.client.side
    }

    get texts() {
      return this.$accessor.chat.texts
    }

    get showBadge() {
      return !this.side && this.readTexts != this.texts
    }

    readTexts: number = 0
    toggleMenu() {
      this.$accessor.client.toggleSide()
      this.readTexts = this.texts
    }

    toggleLock() {
      if (this.admin) {
        if (this.locked) {
          this.$accessor.unlock()
        } else {
          this.$accessor.lock()
        }
      }
    }
  }
</script>

// client/src/layout/Header/Header.tsx
import { useState } from 'react'
import { useStore } from 'zustand'
import { selectIsAdmin } from '@m1k1o/neko'
import { useTranslation } from 'react-i18next'
import { actions } from '@/state/actions'
import { app } from '@/state/app'
import { client, isLocked, type LockResource } from '@/state/client'
import { remember } from '@/state/storage'
import { a11y } from '@/components/a11y'
import { LockButton } from '@/components/LockButton'
import { useSlot } from '@/plugins'
import { EachHook } from '@/components/EachHook'
import logo from '@/assets/images/logo.svg'

const zero = () => 0

export function Header() {
  const { t } = useTranslation()
  const admin = useStore(client.store, selectIsAdmin)
  const settings = useStore(client.store, (s) => s.settings)
  const side = useStore(app, (s) => s.side)
  const items = useSlot('header.item')
  const tabs = useSlot('side.tab')

  const lock = (r: LockResource, icon: string) => {
    const locked = isLocked(r, settings)
    const tip = admin
      ? t(`locks.${r}.${locked ? 'unlock' : 'lock'}`)
      : t(`locks.${r}.${locked ? 'locked' : 'unlocked'}`)
    return (
      <LockButton id={r} icon={icon} locked={locked} admin={admin} tip={tip} onToggle={() => actions.toggleLock(r)} />
    )
  }

  return (
    <div className="flex flex-1 flex-row items-center">
      <a
        href="https://github.com/m1k1o/neko"
        title="Github repository"
        target="_blank"
        rel="noreferrer"
        className="ml-5 flex w-[150px] flex-1 items-center justify-start"
      >
        <img src={logo} alt="n.eko" className="mr-2.5 block h-7.5" />
        <span className="text-[30px] leading-7.5">
          <b className="font-black">n</b>.eko
        </span>
      </a>
      <ul className="mr-2.5 whitespace-nowrap">
        {lock('control', 'fa-mouse')}
        {lock('login', isLocked('login', settings) ? 'fa-lock' : 'fa-lock-open')}
        {items.map(({ id, component: Item }) => (
          <Item key={id} />
        ))}
        {/* what the side panel has to show, for the badge on its toggle */}
        <EachHook items={tabs} use={(tab) => tab.useBadge ?? zero}>
          {(counts) => <Toggle side={side} unread={counts.reduce((n, c) => n + c, 0)} />}
        </EachHook>
      </ul>
    </div>
  )
}

// the side panel's toggle, with a badge when the unread count changed while the panel was closed
function Toggle({ side, unread }: { side: boolean; unread: number }) {
  const [read, setRead] = useState(unread)
  return (
    <li className="mr-2.5 inline-block">
      {!side && read !== unread && (
        <span className="pointer-events-none absolute h-5 w-5 animate-badge rounded-full bg-[red] text-center text-[1.25em] leading-5 font-bold">
          &bull;
        </span>
      )}
      <i
        className="fas fa-bars block h-7.5 w-7.5 cursor-pointer rounded-[3px] bg-background-primary text-center leading-8"
        data-testid="side-toggle"
        {...a11y('Toggle side panel')}
        aria-expanded={side}
        onClick={() => {
          app.setState({ side: !side })
          remember('side', !side)
          setRead(unread)
        }}
      />
    </li>
  )
}
