// src/page/components/chat.vue
<template>
  <div class="chat">
    <ul class="chat-history" ref="history">
      <template v-for="(message, index) in messages" :key="index">
        <li class="message" v-show="neko && neko.connected">
          <div class="content">
            <div class="content-head">
              <span class="session">{{ session(message.id) }}</span>
              <span class="timestamp">{{ timestamp(message.created) }}</span>
            </div>
            <p>{{ message.content }}</p>
          </div>
        </li>
      </template>
    </ul>
    <div class="chat-send">
      <div class="text-container">
        <textarea ref="input" placeholder="Send a message" @keydown="onKeyDown" v-model="content" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
  @import '@/page/assets/styles/main.scss';

  .chat {
    flex: 1;
    flex-direction: column;
    display: flex;
    max-height: 100%;
    max-width: 100%;
    overflow-x: hidden;

    .chat-history {
      flex: 1;
      overflow-y: scroll;
      overflow-x: hidden;
      max-width: 100%;
      scrollbar-width: thin;
      scrollbar-color: $background-tertiary transparent;

      &::-webkit-scrollbar {
        width: 8px;
      }

      &::-webkit-scrollbar-track {
        background-color: transparent;
      }

      &::-webkit-scrollbar-thumb {
        background-color: $background-tertiary;
        border: 2px solid $background-primary;
        border-radius: 4px;
      }

      &::-webkit-scrollbar-thumb:hover {
        background-color: $background-floating;
      }

      .message {
        flex: 1;
        border-top: 1px solid var(--border-color);
        padding: 10px 5px 0px 10px;
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        overflow: hidden;
        user-select: text;
        word-wrap: break-word;
        font-size: 16px;
      }

      .content-head {
        cursor: default;
        width: 100%;
        margin-bottom: 3px;
        display: block;

        .session {
          display: inline-block;
          color: $text-normal;
          font-weight: bold;
        }

        .timestamp {
          color: $text-muted;
          font-size: 0.7rem;
          margin-left: 0.3rem;
          line-height: 12px;
          &::first-letter {
            text-transform: uppercase;
          }
        }
      }
    }

    .chat-send {
      flex-shrink: 0;
      height: 80px;
      max-height: 80px;
      padding: 0 10px 10px 10px;
      flex-direction: column;
      display: flex;

      .text-container {
        flex: 1;
        width: 100%;
        height: 100%;
        background-color: rgba($color: #fff, $alpha: 0.05);
        border-radius: 5px;
        position: relative;
        display: flex;

        .emoji-menu {
          width: 20px;
          height: 20px;
          font-size: 20px;
          margin: 8px 5px 0 0;
          cursor: pointer;
        }

        textarea {
          flex: 1;
          font-family: $text-family;
          border: none;
          caret-color: $text-normal;
          color: $text-normal;
          resize: none;
          margin: 5px;
          background-color: transparent;
          scrollbar-width: thin;
          scrollbar-color: $background-tertiary transparent;

          &::placeholder {
            color: $text-muted;
          }

          &::-webkit-scrollbar {
            width: 4px;
          }

          &::-webkit-scrollbar-track {
            background-color: transparent;
          }

          &::-webkit-scrollbar-thumb {
            background-color: $background-tertiary;
            border-radius: 4px;
          }

          &::-webkit-scrollbar-thumb:hover {
            background-color: $background-floating;
          }

          &::selection {
            background: $text-link;
          }
        }
      }
    }
  }
</style>

<script lang="ts" setup>
import { ref, watch, onMounted } from 'vue'
import Neko from '@/component/main.vue'

const length = 512 // max length of message

const history = ref<HTMLUListElement | null>(null)

const props = defineProps<{
  neko: typeof Neko
}>()

const emit = defineEmits(['send_message'])

type Message = {
  id: string
  created: Date
  content: string
}

const messages = ref<Message[]>([])
const content = ref('')

onMounted(() => {
  setTimeout(() => {
    history.value!.scrollTop = history.value!.scrollHeight
  }, 0)
})

function timestamp(date: Date | string) {
  date = new Date(date)

  return (
    date.getFullYear() +
    '-' +
    String(date.getMonth() + 1).padStart(2, '0') +
    '-' +
    String(date.getDate()).padStart(2, '0') +
    ' ' +
    String(date.getHours()).padStart(2, '0') +
    ':' +
    String(date.getMinutes()).padStart(2, '0') +
    ':' +
    String(date.getSeconds()).padStart(2, '0')
  )
}

function session(id: string) {
  let session = props.neko.state.sessions[id]
  return session ? session.profile.name : id
}

function onNekoChange() {
  props.neko.events.on('receive.broadcast', (sender: string, subject: string, body: any) => {
    if (subject === 'chat') {
      const message = body as Message
      messages.value = [...messages.value, message]
    }
  })
}

watch(() => props.neko, onNekoChange)

function onHistroyChange() {
  setTimeout(() => {
    history.value!.scrollTop = history.value!.scrollHeight
  }, 0)
}

watch(messages, onHistroyChange)

function onKeyDown(event: KeyboardEvent) {
  if (content.value.length > length) {
    content.value = content.value.substring(0, length)
  }

  if (content.value.length == length) {
    if (
      [8, 16, 17, 18, 20, 33, 34, 35, 36, 37, 38, 39, 40, 45, 46, 91, 93, 144].includes(event.keyCode) ||
      (event.ctrlKey && [67, 65, 88].includes(event.keyCode))
    ) {
      return
    }
    event.preventDefault()
    return
  }

  if (event.keyCode !== 13 || event.shiftKey) {
    return
  }

  if (content.value === '') {
    event.preventDefault()
    return
  }

  emit('send_message', content.value)

  let message = {
    id: props.neko.state.session_id,
    created: new Date(),
    content: content.value,
  }
  
  props.neko.sendBroadcast('chat', message)
  messages.value = [...messages.value, message]

  content.value = ''
  event.preventDefault()
}
</script>

// client/src/plugins/chat/Chat.tsx
import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useStore } from 'zustand'
import { useShallow } from 'zustand/react/shallow'
import { useTranslation } from 'react-i18next'
import { openMenu } from '@/state/actions'
import { client, selectMuted } from '@/state/client'
import { cn } from '@/lib/utils'
import { a11y } from '@/components/a11y'
import { Avatar } from '@/components/Avatar'
import { chat } from './store'
import { sendChat } from './actions'
import { loadEmoji } from './emoji'
import { Markdown } from './Markdown'
import { EmojiPicker } from './EmojiPicker'
import './emoji-sprites.scss'

const time = (d: Date) =>
  d.toDateString() === new Date().toDateString()
    ? `Today at ${d.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}`
    : d.toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })

const MAX_MESSAGE = 512
// a line of the history: a message (an avatar and the content) or an event
const line = 'flex flex-1 flex-row flex-nowrap overflow-hidden pt-2.5 pr-[5px] pl-2.5 wrap-break-word select-text'

export function Chat() {
  const { t } = useTranslation()
  const sessions = useStore(client.store, (s) => s.sessions)
  const muted = useStore(client.store, selectMuted)
  const { lines, enabled } = useStore(
    chat,
    useShallow((s) => ({ lines: s.lines, enabled: s.enabled })),
  )
  const [text, setText] = useState('')
  const [picker, setPicker] = useState(false)
  const history = useRef<HTMLUListElement>(null)
  const input = useRef<HTMLTextAreaElement>(null)

  useEffect(loadEmoji, [])
  const last = lines[lines.length - 1]?.seq
  useLayoutEffect(() => {
    history.current!.scrollTop = history.current!.scrollHeight
  }, [last])

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key !== 'Enter' || e.shiftKey || e.nativeEvent.isComposing) return
    e.preventDefault()
    if (!text.trim()) return
    sendChat(text)
    setText('')
  }

  // insert :name: at the cursor, like the legacy picker
  const onEmoji = (name: string) => {
    const el = input.current!
    const code = `:${name}:`
    const at = el.selectionStart ?? text.length
    const next = (text.slice(0, at) + code + text.slice(el.selectionEnd ?? at)).slice(0, MAX_MESSAGE)
    setText(next)
    setPicker(false)
    requestAnimationFrame(() => {
      el.focus()
      el.selectionStart = el.selectionEnd = at + code.length
    })
  }

  const nameOf = (m: (typeof lines)[number]) => sessions[m.id]?.profile.name ?? m.name
  return (
    <div className="flex max-h-full max-w-full flex-1 flex-col overflow-x-hidden" data-testid="chat">
      <ul
        className="max-w-full flex-1 overflow-x-hidden overflow-y-scroll selection:bg-text-link [scrollbar-color:var(--color-background-tertiary)_transparent] [scrollbar-width:thin]"
        ref={history}
      >
        {lines.map((m, i) => {
          const bulk = i > 0 && lines[i - 1].id === m.id && lines[i - 1].type === 'text'
          return m.type === 'text' ? (
            <li key={m.seq} className={cn(line, 'text-[16px]', bulk ? 'pt-0' : 'pt-[15px]')} data-testid="chat-message">
              <div
                className={cn(
                  'mr-2.5 h-10 w-10 shrink-0 grow-0 overflow-hidden rounded-full bg-style-primary',
                  bulk && 'invisible h-0',
                )}
                data-testid="chat-author"
                onContextMenu={(e) => openMenu(e, m.id)}
              >
                <Avatar seed={nameOf(m)} avatar={sessions[m.id]?.profile.avatar} size={40} />
              </div>
              <div className="flex min-w-0 flex-1 flex-col wrap-break-word">
                {!bulk && (
                  <div className="mb-[3px] block w-full cursor-default">
                    <span className="inline-block font-medium text-text-normal">{nameOf(m)}</span>
                    {/* the legacy 0.7rem and 0.3rem at a 14px root */}
                    <span
                      className="ml-[4.2px] inline-block text-[9.8px] leading-3 font-medium text-text-muted first-letter:uppercase"
                      data-testid="chat-time"
                    >
                      {time(m.created)}
                    </span>
                  </div>
                )}
                <Markdown source={m.content} />
              </div>
            </li>
          ) : (
            <li key={m.seq} className={cn(line, 'cursor-default text-text-muted')} data-testid="chat-event">
              <div className="inline-block min-w-0 align-baseline leading-5 wrap-break-word" title={time(m.created)}>
                <strong className="font-semibold">{m.name}</strong> {m.content}
              </div>
            </li>
          )
        })}
      </ul>
      {enabled && !muted && (
        <div className="flex h-[90px] max-h-[90px] shrink-0 flex-col px-2.5 pb-2.5">
          <div className="mt-[5px] mb-2.5 h-px w-full bg-white/5" />
          <div className="relative flex h-full w-full flex-1 rounded-[5px] bg-white/5">
            <textarea
              ref={input}
              className="m-[5px] flex-1 resize-none border-0 bg-transparent text-text-normal caret-text-normal selection:bg-text-link placeholder:text-text-muted [scrollbar-color:var(--color-background-tertiary)_transparent] [scrollbar-width:thin]"
              data-testid="chat-input"
              placeholder={t('chat:send_a_message')}
              maxLength={MAX_MESSAGE}
              value={text}
              onChange={(e) => setText(e.target.value)}
              onKeyDown={onKeyDown}
            />
            {picker && <EmojiPicker onPick={onEmoji} onClose={() => setPicker(false)} />}
            <i
              className="fas fa-laugh mt-2 mr-[5px] h-5 w-5 cursor-pointer text-[20px]"
              data-testid="emoji-open"
              {...a11y('Emoji')}
              onClick={(e) => (e.stopPropagation(), setPicker(!picker))}
            />
          </div>
        </div>
      )}
    </div>
  )
}
