// client/src/components/avatar.vue
<template>
  <!--
      <img :src="`https://ui-avatars.com/api/?name=${seed}&size=${size}`" />
  -->
  <div
    class="avatar"
    :style="{
      width: size + 'px',
      height: size + 'px',
      lineHeight: size + 'px',
      fontSize: size / 2 + 'px',
      backgroundColor: Background(seed),
    }"
  >
    <img v-if="imageURL" :src="imageURL" :alt="seed" @error="imageFailed = true" />
    <template v-else>{{ seed.substring(0, 2).toUpperCase() }}</template>
  </div>
</template>

<style lang="scss" scoped>
  .avatar {
    user-select: none;
    text-align: center;
    background: white;
    color: black;
    display: inline-block;
    overflow: hidden;
    border-radius: 50%;

    img {
      width: 100%;
      height: 100%;
      display: block;
      object-fit: cover;
    }
  }
</style>

<script lang="ts">
  import { Vue, Component, Prop, Watch } from 'vue-property-decorator'

  @Component({
    name: 'neko-avatar',
  })
  export default class extends Vue {
    @Prop(String) readonly seed: string | undefined
    @Prop(String) readonly avatar: string | undefined
    @Prop(Number) readonly size: number | undefined

    private imageFailed: boolean = false

    get imageURL(): string {
      if (this.imageFailed || !this.avatar) {
        return ''
      }

      try {
        const avatar = new URL(this.avatar)
        return avatar.protocol === 'http:' || avatar.protocol === 'https:' ? avatar.toString() : ''
      } catch (_) {
        return ''
      }
    }

    @Watch('avatar')
    onAvatarChanged() {
      this.imageFailed = false
    }

    Background(seed: string) {
      let a = 0,
        b = 0,
        c = 0

      for (let i = 0; i < seed.length; i++) {
        a += seed.charCodeAt(i) * 3
        b += seed.charCodeAt(i) * 5
        c += seed.charCodeAt(i) * 7
      }

      let x = Math.floor(128 + (a % 128))
      let y = Math.floor(128 + (b % 128))
      let z = Math.floor(128 + (c % 128))
      return 'rgb(' + x + ',' + y + ',' + z + ')'
    }
  }
</script>

// client/src/components/Avatar/Avatar.tsx
import { useEffect, useState } from 'react'

export function Avatar({ seed, avatar, size }: { seed: string; avatar?: string; size: number }) {
  const [failed, setFailed] = useState(false)
  useEffect(() => setFailed(false), [avatar])

  let url = ''
  try {
    const u = new URL(avatar || '')
    if (u.protocol === 'http:' || u.protocol === 'https:') url = u.toString()
  } catch {}

  // deterministic pastel color from the name, same formula as the legacy client
  let a = 0,
    b = 0,
    c = 0
  for (let i = 0; i < seed.length; i++) {
    a += seed.charCodeAt(i) * 3
    b += seed.charCodeAt(i) * 5
    c += seed.charCodeAt(i) * 7
  }
  const bg = `rgb(${128 + (a % 128)},${128 + (b % 128)},${128 + (c % 128)})`

  return (
    <div
      className="inline-block overflow-hidden rounded-full bg-white text-center text-black select-none"
      style={{ width: size, height: size, lineHeight: size + 'px', fontSize: size / 2, backgroundColor: bg }}
    >
      {url && !failed ? (
        <img src={url} alt={seed} className="block h-full w-full object-cover" onError={() => setFailed(true)} />
      ) : (
        seed.substring(0, 2).toUpperCase()
      )}
    </div>
  )
}
