// client/src/features/emotes/Emote.tsx
import { useEffect, useRef } from 'react'
import { hideEmote } from '@/state/emotes'
import './sprites.css'

const rnd = (a: number, b: number) => a + Math.random() * (b - a)

// one emote flying over the video: seven copies float up and fade, like the legacy anime.js version
export function Emote({ id, type }: { id: string; type: string }) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const anims = [...ref.current!.children].map((el, i) => {
      const side = (odd: boolean) => (odd ? rnd(0, 50) : rnd(-50, 0)) + '%'
      return (el as HTMLElement).animate(
        [
          { left: side(!!(i % 2)), top: '0%', opacity: 0, transform: 'rotate(0deg)' },
          { left: side(!!(i % 2)), opacity: 1, offset: 0.33 },
          { left: side(!(i % 2)), opacity: 0.5, offset: 0.66 },
          { left: side(!!(i % 2)), top: rnd(-600, -200) + '%', opacity: 0, transform: `rotate(${rnd(-35, 35)}deg)` },
        ],
        { duration: rnd(1000, 2000), easing: 'ease-in-out', fill: 'forwards' },
      ).finished
    })
    Promise.all(anims).then(() => hideEmote(id))
  }, [id])
  return (
    <div ref={ref} className="absolute right-0 bottom-0 h-[10%] w-1/4" data-testid="emote-animation">
      {Array.from({ length: 7 }, (_, i) => (
        <div
          key={i}
          className={`emote ${type} absolute h-full w-[100px] scale-[0.7] bg-contain text-center text-white`}
        />
      ))}
    </div>
  )
}

// client/src/components/emote.vue
<template>
  <div ref="emote" @click.stop.prevent="run" class="emote-container">
    <div :class="classes" />
    <div :class="classes" />
    <div :class="classes" />
    <div :class="classes" />
    <div :class="classes" />
    <div :class="classes" />
    <div :class="classes" />
  </div>
</template>

<style lang="scss" scoped>
  .emote-container {
    width: 25%;
    height: 10%;
    position: absolute;
    bottom: 0;
    right: 0;

    .emote {
      position: absolute;
      width: 100px;
      height: 100%;
      color: #fff;
      transform: scale(0.7);
      text-align: center;
      background-size: contain;
    }
  }
</style>

<script lang="ts">
  import { Component, Ref, Vue, Prop } from 'vue-property-decorator'

  @Component({ name: 'neko-emote' })
  export default class extends Vue {
    @Prop({
      required: true,
    })
    id!: string

    @Ref('emote') container!: HTMLElement

    get emote() {
      return this.$accessor.chat.emotes[this.id]
    }

    private classes: string[] = []

    mounted() {
      const range = 50
      let count = 0
      let finish: Array<Promise<any>> = []

      this.classes = ['emote', this.emote.type]

      for (let child of this.container.children) {
        const ele = child as HTMLElement
        ele.style['left'] = `${count % 2 ? this.$anime.random(0, range) : this.$anime.random(-range, 0)}%`
        ele.style['opacity'] = `0`

        const animation = this.$anime({
          targets: child,
          keyframes: [
            { left: `${count % 2 ? this.$anime.random(0, range) : this.$anime.random(-range, 0)}%`, opacity: 1 },
            { left: `${count % 2 ? this.$anime.random(-range, 0) : this.$anime.random(0, range)}%`, opacity: 0.5 },
            { left: `${count % 2 ? this.$anime.random(0, range) : this.$anime.random(-range, 0)}%`, opacity: 0 },
          ],
          elasticity: 600,
          rotate: this.$anime.random(-35, 35),
          top: `${this.$anime.random(-200, -600)}%`,
          duration: this.$anime.random(1000, 2000),
          easing: 'easeInOutQuad',
        })

        count++
        finish.push(animation.finished)
      }

      Promise.all(finish).then(() => {
        this.$emit('done', this.id)
        this.$accessor.chat.delEmote(this.id)
      })
    }
  }
</script>
