// client/src/plugins/filetransfer/Files.tsx
import { useRef, useState } from 'react'
import { useStore } from 'zustand'
import { useShallow } from 'zustand/react/shallow'
import { selectIsAdmin } from '@m1k1o/neko'
import { useTranslation } from 'react-i18next'
import { client } from '@/state/client'
import { ask } from '@/state/dialogs'
import { cn } from '@/lib/utils'
import { a11y } from '@/components/a11y'
import { store, type FileItem } from './store'
import { fileUrl, fileDelete, refresh, upload } from './actions'

const box = 'rounded-[5px] bg-white/5'
const action = 'cursor-pointer font-semibold text-white/60 transition-colors duration-200 hover:text-white'
const name = 'overflow-hidden text-ellipsis whitespace-nowrap'
// the file and transfer lists scroll with a thin bar
const scroll = '[scrollbar-color:var(--color-background-tertiary)_transparent] [scrollbar-width:thin]'

const size = (bytes?: number) => {
  if (bytes === undefined) return ''
  const u = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = bytes > 0 ? Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), u.length - 1) : 0
  return `${+(bytes / 1024 ** i).toFixed(i ? 1 : 0)} ${u[i]}`
}

export function Files() {
  const { t } = useTranslation()
  const { files: f, uploads } = useStore(
    store,
    useShallow((s) => ({ files: s.files!, uploads: s.uploads })),
  )
  const admin = useStore(client.store, selectIsAdmin)
  const [drag, setDrag] = useState(false)
  const [selecting, setSelecting] = useState(false)
  const [selected, setSelected] = useState<string[]>([])
  const input = useRef<HTMLInputElement>(null)

  const canDownload = admin || f.user_download
  const canUpload = admin || f.user_upload
  const canDelete = admin || f.user_delete
  const files = f.files ?? []
  const plain = files.filter((x) => x.type !== 'dir')
  const allSelected = plain.length > 0 && plain.every((x) => selected.includes(x.name))

  const toggle = (n: string) => setSelected((s) => (s.includes(n) ? s.filter((x) => x !== n) : [...s, n]))
  const stopSelecting = () => (setSelecting(false), setSelected([]))
  const onItemClick = (item: FileItem, e: React.MouseEvent) => {
    if (item.type === 'dir') return
    if (e.ctrlKey || e.metaKey) {
      setSelecting(true)
      toggle(item.name)
    } else if (selecting) toggle(item.name)
  }
  const deleteOne = (n: string) =>
    ask(t('files:delete_title', { name: n }), t('files:delete_confirm')).then((ok) => ok && fileDelete(n))
  const deleteSelected = async () => {
    if (!(await ask(t('files:delete_selected_title'), t('files:delete_selected_confirm', { count: selected.length }))))
      return
    const names = selected
    stopSelecting()
    for (const n of names) await fileDelete(n)
  }

  return (
    <div className="flex max-w-full flex-1 flex-col">
      <div className={cn(box, 'mx-2.5 mt-2.5 flex flex-row p-2 font-semibold')}>
        <p>{f.root_dir}</p>
        <i className="fas fa-rotate-right ml-auto cursor-pointer" {...a11y('Refresh')} onClick={refresh} />
      </div>
      {plain.length > 2 && canDelete && (
        <div className={cn(box, 'mx-2.5 mt-2.5 flex flex-row items-center justify-between p-2 text-[0.9em]')}>
          <div className="flex items-center">
            {!selecting ? (
              <span className={action} role="button" tabIndex={0} onClick={() => setSelecting(true)}>
                {t('files:select')}
              </span>
            ) : (
              <span
                className={action}
                role="button"
                tabIndex={0}
                onClick={() => setSelected(allSelected ? [] : plain.map((x) => x.name))}
              >
                {t(allSelected ? 'files:unselect_all' : 'files:select_all')}
              </span>
            )}
          </div>
          {selecting && (
            <div className="flex items-center gap-[1.2em]">
              {selected.length > 0 && (
                <span
                  className={cn(action, 'text-style-error hover:text-[#dc5959]')}
                  role="button"
                  tabIndex={0}
                  onClick={deleteSelected}
                >
                  <i className="fas fa-trash"></i> {t('files:delete')} ({selected.length})
                </span>
              )}
              <span className={action} role="button" tabIndex={0} onClick={stopSelecting}>
                {t('files:cancel')}
              </span>
            </div>
          )}
        </div>
      )}
      <div className={cn(box, 'm-2.5 overflow-y-scroll', scroll)}>
        {files.map((item) => {
          const sel = selecting && item.type !== 'dir'
          return (
            <div
              key={item.name}
              className={cn(
                'flex flex-row border-b-2 border-white/10 p-2 leading-[1.2] last:border-b-0',
                sel && 'cursor-pointer transition-colors duration-200 hover:bg-white/8',
                sel && selected.includes(item.name) && 'bg-white/12',
              )}
              data-testid="file"
              onClick={(e) => onItemClick(item, e)}
            >
              {sel && (
                <input
                  type="checkbox"
                  className="mr-[0.8em] cursor-pointer accent-style-primary"
                  checked={selected.includes(item.name)}
                  onClick={(e) => e.stopPropagation()}
                  onChange={() => toggle(item.name)}
                />
              )}
              <i className={`fas ${item.type === 'dir' ? 'fa-folder' : 'fa-file'} mr-2 w-3.5`} />
              <p className={name} data-testid="file-name" title={item.name}>
                {item.name}
              </p>
              <p className="mr-2 ml-auto whitespace-nowrap text-white/40">{size(item.size)}</p>
              {/* native download: the browser's download manager shows progress */}
              {!selecting && item.type !== 'dir' && canDownload && (
                <a href={fileUrl(item.name)} download={item.name}>
                  <i className="fas fa-download cursor-pointer" aria-label={`Download ${item.name}`} />
                </a>
              )}
              {!selecting && item.type !== 'dir' && canDelete && (
                <i
                  className="fas fa-trash ml-2 cursor-pointer"
                  data-testid="file-delete"
                  {...a11y(`${t('files:delete')} ${item.name}`)}
                  onClick={() => deleteOne(item.name)}
                />
              )}
            </div>
          )
        })}
      </div>
      <div className="mt-auto">
        {uploads.length > 0 && (
          <div className={cn(box, 'm-2.5 max-h-[50vh] overflow-x-hidden overflow-y-scroll', scroll)}>
            <p className="flex justify-between border-b-2 border-white/10 p-2.5 font-semibold">
              <span>{t('files:uploads')}</span>
              <i
                className="fas fa-xmark cursor-pointer"
                {...a11y('Clear finished uploads')}
                onClick={() => store.setState((s) => ({ uploads: s.uploads.filter((u) => u.status === 'inprogress') }))}
              />
            </p>
            {uploads.map((u) => (
              <div key={u.id} data-testid="transfer" data-status={u.status}>
                <div className="flex max-w-full flex-row p-2.5">
                  <i
                    className={`fas ${u.status === 'inprogress' ? 'fa-arrows-rotate' : u.status === 'completed' ? 'fa-check' : 'fa-warning'} mr-2 w-3.5`}
                  />
                  <p className={name} title={u.name}>
                    {u.name}
                  </p>
                  <p className="mr-2 ml-auto whitespace-nowrap text-white/40">
                    {Math.min(100, Math.round((u.progress / (u.size || 1)) * 100))}%
                  </p>
                </div>
                {u.status === 'failed' ? (
                  <div className="rounded-[5px] border border-style-error p-2.5">{u.error}</div>
                ) : (
                  <progress
                    className="mx-2.5 mb-2.5 h-3.5 w-[95%] appearance-none overflow-hidden rounded-full [&::-moz-progress-bar]:bg-style-primary [&::-webkit-progress-bar]:bg-background-tertiary [&::-webkit-progress-value]:bg-style-primary"
                    value={u.progress}
                    max={u.size}
                  />
                )}
              </div>
            ))}
          </div>
        )}
        {canUpload && (
          <div
            className={cn(
              box,
              'm-2.5 flex cursor-pointer flex-col justify-center text-center hover:bg-white/10',
              drag && 'bg-white/10',
            )}
            data-testid="upload"
            onDragOver={(e) => (e.preventDefault(), setDrag(true))}
            onDragLeave={(e) => (e.preventDefault(), setDrag(false))}
            onDrop={(e) => (e.preventDefault(), setDrag(false), upload(e.dataTransfer.files))}
            {...a11y(t('files:upload_here'))}
            onClick={() => input.current!.click()}
          >
            <i className="fas fa-file-arrow-up m-2.5 text-[4em]" />
            <p className="mx-2.5 mb-2.5">{t('files:upload_here')}</p>
            <input
              ref={input}
              type="file"
              multiple
              hidden
              onChange={(e) => {
                if (e.target.files) upload(e.target.files)
                e.target.value = '' // so the same file can be chosen again
              }}
            />
          </div>
        )}
      </div>
    </div>
  )
}

// client/src/components/files.vue
<template>
  <div class="files">
    <div class="files-cwd">
      <p>{{ cwd }}</p>
      <i class="fas fa-rotate-right refresh" @click="refresh" />
    </div>
    <div class="files-actions" v-if="files.filter((f) => f.type !== 'dir').length > 2">
      <div class="left-controls">
        <span v-if="!selectionMode" class="action-btn select-toggle" @click="toggleSelectionMode">
          {{ tWithFallback('files.select', 'Select') }}
        </span>
        <span v-else class="action-btn select-all" @click="toggleSelectAll">
          {{
            isAllSelected
              ? tWithFallback('files.unselect_all', 'Unselect All')
              : tWithFallback('files.select_all', 'Select All')
          }}
        </span>
      </div>
      <div v-if="selectionMode" class="right-controls">
        <span class="action-btn delete-selected" v-if="selectedFiles.length > 0" @click="deleteSelectedFiles">
          <i class="fas fa-trash"></i> {{ tWithFallback('files.delete', 'Delete') }} ({{ selectedFiles.length }})
        </span>
        <span class="action-btn select-toggle cancel-btn" @click="toggleSelectionMode">
          {{ tWithFallback('files.cancel', 'Cancel') }}
        </span>
      </div>
    </div>
    <div class="files-list">
      <div
        v-for="item in files"
        :key="item.name"
        class="files-list-item"
        :class="{
          'selectable-item': selectionMode && item.type !== 'dir',
          'selected-item': selectionMode && isSelected(item.name),
        }"
        @click="onItemClick(item)"
      >
        <input
          v-if="selectionMode && item.type !== 'dir'"
          type="checkbox"
          class="file-checkbox"
          :checked="isSelected(item.name)"
          @change.stop="toggleSelectFile(item.name)"
        />
        <i :class="fileIcon(item)" />
        <p class="file-name" :title="item.name">{{ item.name }}</p>
        <p class="file-size">{{ fileSize(item.size) }}</p>
        <i
          v-if="!selectionMode && item.type !== 'dir' && canDownload"
          class="fas fa-download download"
          @click="download(item)"
        />
        <i
          v-if="!selectionMode && item.type !== 'dir' && canDelete"
          class="fas fa-trash delete"
          :title="$t('files.delete')"
          @click="deleteFile(item)"
        />
      </div>
    </div>
    <div class="transfer-area">
      <div class="transfers" v-if="transfers.length > 0">
        <p v-if="downloads.length > 0" class="transfers-list-header">
          <span>{{ $t('files.downloads') }}</span>
          <i class="fas fa-xmark remove-transfer" @click="downloads.forEach((t) => removeTransfer(t))"></i>
        </p>
        <div v-for="download in downloads" :key="download.id" class="transfers-list-item">
          <div class="transfer-info">
            <i
              class="fas transfer-status"
              :class="{
                'fa-clock': download.status === 'pending',
                'fa-arrows-rotate': download.status === 'inprogress',
                'fa-check': download.status === 'completed',
                'fa-warning': download.status === 'failed',
              }"
            ></i>
            <p class="file-name" :title="download.name">{{ download.name }}</p>
            <p class="file-size">{{ Math.min(100, Math.round((download.progress / download.size) * 100)) }}%</p>
            <i class="fas fa-xmark remove-transfer" @click="removeTransfer(download)"></i>
          </div>
          <div v-if="download.status === 'failed'" class="transfer-error">{{ download.error }}</div>
          <progress
            v-else
            class="transfer-progress"
            :aria-label="download.name + ' progress'"
            :value="download.progress"
            :max="download.size"
          ></progress>
        </div>
        <p v-if="uploads.length > 0" class="transfers-list-header">
          <span>{{ $t('files.uploads') }}</span>
          <i class="fas fa-xmark remove-transfer" @click="uploads.forEach((t) => removeTransfer(t))"></i>
        </p>
        <div v-for="upload in uploads" :key="upload.id" class="transfers-list-item">
          <div class="transfer-info">
            <i
              class="fas transfer-status"
              :title="upload.status"
              :class="{
                'fa-clock': upload.status === 'pending',
                'fa-arrows-rotate': upload.status === 'inprogress',
                'fa-check': upload.status === 'completed',
                'fa-warning': upload.status === 'failed',
              }"
            ></i>
            <p class="file-name" :title="upload.name">{{ upload.name }}</p>
            <p class="file-size">{{ Math.min(100, Math.round((upload.progress / upload.size) * 100)) }}%</p>
            <i class="fas fa-xmark remove-transfer" @click="removeTransfer(upload)"></i>
          </div>
          <div v-if="upload.status === 'failed'" class="transfer-error">{{ upload.error }}</div>
          <progress
            v-else
            class="transfer-progress"
            :aria-label="upload.name + ' progress'"
            :value="upload.progress"
            :max="upload.size"
          ></progress>
        </div>
      </div>
      <div
        v-if="canUpload"
        class="upload-area"
        :class="{ 'upload-area-drag': uploadAreaDrag }"
        @dragover.prevent="uploadAreaDrag = true"
        @dragleave.prevent="uploadAreaDrag = false"
        @drop.prevent="(e) => upload(e.dataTransfer)"
        @click="openFileBrowser"
      >
        <i class="fas fa-file-arrow-up" />
        <p>{{ $t('files.upload_here') }}</p>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
  .files {
    flex: 1;
    flex-direction: column;
    display: flex;
    max-width: 100%;

    .files-cwd {
      display: flex;
      flex-direction: row;
      margin: 10px 10px 0px 10px;
      padding: 0.5em;
      font-weight: 600;
      background-color: rgba($color: #fff, $alpha: 0.05);
      border-radius: 5px;
    }

    .files-actions {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
      margin: 10px 10px 0px 10px;
      padding: 0.5em;
      background-color: rgba($color: #fff, $alpha: 0.05);
      border-radius: 5px;
      font-size: 0.9em;

      .left-controls {
        display: flex;
        align-items: center;
      }

      .right-controls {
        display: flex;
        gap: 1.2em;
        align-items: center;
      }

      .action-btn {
        cursor: pointer;
        font-weight: 600;
        color: rgba($color: #fff, $alpha: 0.6);
        transition: color 0.2s ease;

        &:hover {
          color: #fff;
        }

        &.delete-selected {
          color: $style-error;

          &:hover {
            color: lighten($style-error, 10%);
          }
        }
      }
    }

    .files-list {
      margin: 10px 10px 10px 10px;
      background-color: rgba($color: #fff, $alpha: 0.05);
      border-radius: 5px;
      overflow-y: scroll;
      scrollbar-width: thin;
      scrollbar-color: $background-tertiary transparent;

      &::-webkit-scrollbar {
        width: 8px;
      }

      &::-webkit-scrollbar-track {
        background-color: transparent;
      }

      &::-webkit-scrollbar-thumb {
        background-color: $background-tertiary;
        border: 2px solid $background-primary;
        border-radius: 4px;
      }

      &::-webkit-scrollbar-thumb:hover {
        background-color: $background-floating;
      }
    }

    .files-list-item {
      padding: 0.5em;
      border-bottom: 2px solid rgba($color: #fff, $alpha: 0.1);
      display: flex;
      flex-direction: row;
      line-height: 1.2;
    }

    .file-checkbox {
      margin-right: 0.8em;
      cursor: pointer;
      accent-color: $style-primary;
    }

    .selectable-item {
      cursor: pointer;
      transition: background-color 0.2s ease;

      &:hover {
        background-color: rgba($color: #fff, $alpha: 0.08);
      }

      &.selected-item {
        background-color: rgba($color: #fff, $alpha: 0.12);
      }
    }

    .transfers-list-header {
      display: flex;
      justify-content: space-between;
      border-bottom: 2px solid rgba($color: #fff, $alpha: 0.1);
    }

    .file-icon,
    .transfer-status {
      width: 14px;
      margin-right: 0.5em;
    }

    .transfer-error {
      border: 1px solid $style-error;
      border-radius: 5px;
      padding: 10px;
    }

    .files-list-item:last-child {
      border-bottom: 0px;
    }

    .refresh {
      margin-left: auto;
    }

    .file-name {
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
    }

    .file-size {
      margin-left: auto;
      margin-right: 0.5em;
      color: rgba($color: #fff, $alpha: 0.4);
      white-space: nowrap;
    }

    .refresh:hover,
    .download:hover,
    .delete:hover,
    .remove-transfer:hover {
      cursor: pointer;
    }

    .delete {
      margin-left: 0.5em;
    }

    .transfer-area {
      margin-top: auto;
    }

    .transfers {
      margin: 10px 10px 10px 10px;
      background-color: rgba($color: #fff, $alpha: 0.05);
      border-radius: 5px;
      max-height: 50vh;
      overflow-y: scroll;
      overflow-x: hidden;
      scrollbar-width: thin;
      scrollbar-color: $background-tertiary transparent;

      &::-webkit-scrollbar {
        width: 8px;
      }

      &::-webkit-scrollbar-track {
        background-color: transparent;
      }

      &::-webkit-scrollbar-thumb {
        background-color: $background-tertiary;
        border: 2px solid $background-primary;
        border-radius: 4px;
      }

      &::-webkit-scrollbar-thumb:hover {
        background-color: $background-floating;
      }
    }

    .transfers > p {
      padding: 10px;
      font-weight: 600;
    }

    .transfer-info {
      display: flex;
      flex-direction: row;
      max-width: 100%;
      padding: 10px;
    }

    .transfer-progress {
      margin: 0px 10px 10px 10px;
      width: 95%;
    }

    .upload-area {
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
      margin: 10px 10px 10px 10px;
      background-color: rgba($color: #fff, $alpha: 0.05);
      border-radius: 5px;
    }

    .upload-area:hover {
      cursor: pointer;
    }

    .upload-area-drag,
    .upload-area:hover {
      background-color: rgba($color: #fff, $alpha: 0.1);
    }

    .upload-area > i {
      font-size: 4em;
      margin: 10px 10px 10px 10px;
    }

    .upload-area > p {
      margin: 0px 10px 10px 10px;
    }
  }
</style>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator'

  import Markdown from './markdown'
  import Content from './context.vue'
  import { FileTransfer, FileListItem } from '~/neko/types'

  @Component({
    name: 'neko-files',
    components: {
      'neko-markdown': Markdown,
      'neko-context': Content,
    },
  })
  export default class extends Vue {
    public uploadAreaDrag: boolean = false
    public selectionMode: boolean = false
    public selectedFiles: string[] = []

    toggleSelectionMode() {
      this.selectionMode = !this.selectionMode
      if (!this.selectionMode) {
        this.selectedFiles = []
      }
    }

    isSelected(name: string) {
      return this.selectedFiles.includes(name)
    }

    toggleSelectFile(name: string) {
      const index = this.selectedFiles.indexOf(name)
      if (index > -1) {
        this.selectedFiles.splice(index, 1)
      } else {
        this.selectedFiles.push(name)
      }
    }

    onItemClick(item: FileListItem) {
      if (this.selectionMode && item.type !== 'dir') {
        this.toggleSelectFile(item.name)
      }
    }

    get isAllSelected() {
      const nonDirFiles = this.files.filter((f) => f.type !== 'dir')
      if (nonDirFiles.length === 0) return false
      return nonDirFiles.every((f) => this.isSelected(f.name))
    }

    toggleSelectAll() {
      const nonDirFiles = this.files.filter((f) => f.type !== 'dir')
      if (this.isAllSelected) {
        this.selectedFiles = []
      } else {
        this.selectedFiles = nonDirFiles.map((f) => f.name)
      }
    }

    tWithFallback(key: string, fallback: string, formatData?: any) {
      const translated = this.$t(key, formatData)
      if (translated === key) {
        if (formatData) {
          let str = fallback
          for (const k of Object.keys(formatData)) {
            str = str.replace(`{${k}}`, formatData[k])
          }
          return str
        }
        return fallback
      }
      return translated as string
    }

    async deleteSelectedFiles() {
      if (this.selectedFiles.length === 0) return

      const count = this.selectedFiles.length
      const { isConfirmed } = await this.$swal({
        title: this.tWithFallback('files.delete_selected_title', 'Delete selected files?'),
        text: this.tWithFallback(
          'files.delete_selected_confirm',
          'Do you really want to remove the {count} selected files?',
          { count },
        ),
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: this.$t('context.confirm.button_yes') as string,
        cancelButtonText: this.$t('context.confirm.button_cancel') as string,
      })
      if (!isConfirmed) {
        return
      }

      const filesToRemove = [...this.selectedFiles]
      this.selectionMode = false
      this.selectedFiles = []

      for (const name of filesToRemove) {
        const url = '/file?pwd=' + encodeURIComponent(this.$accessor.password) + '&filename=' + encodeURIComponent(name)
        try {
          await this.$http.delete(url)
        } catch (error: any) {
          this.$log.error(new Error(`Failed to delete ${name}: ${error.message || error}`))
        }
      }
      this.$accessor.files.refresh()
    }

    get canDownload() {
      return this.$accessor.user.admin || this.$accessor.files.userDownload
    }

    get canDelete() {
      return this.$accessor.user.admin || this.$accessor.files.userDelete
    }

    get canUpload() {
      return this.$accessor.user.admin || this.$accessor.files.userUpload
    }

    get cwd() {
      return this.$accessor.files.cwd
    }

    get files() {
      return this.$accessor.files.files
    }

    get transfers() {
      return this.$accessor.files.transfers
    }

    get downloads() {
      return this.$accessor.files.transfers.filter((t) => t.direction === 'download')
    }

    get uploads() {
      return this.$accessor.files.transfers.filter((t) => t.direction === 'upload')
    }

    refresh() {
      this.$accessor.files.refresh()
    }

    download(item: FileListItem) {
      if (this.downloads.map((t) => t.name).includes(item.name)) {
        return
      }

      const url =
        '/file?pwd=' + encodeURIComponent(this.$accessor.password) + '&filename=' + encodeURIComponent(item.name)
      const abortController = new AbortController()

      let transfer: FileTransfer = {
        id: Math.round(Math.random() * 10000),
        name: item.name,
        direction: 'download',
        // this may be smaller than the actual transfer amount, but for large files the
        // content length is not sent (chunked transfer)
        size: item.size,
        progress: 0,
        status: 'pending',
        abortController: abortController,
      }

      this.$http
        .get(url, {
          responseType: 'blob',
          signal: abortController.signal,
          withCredentials: false,
          onDownloadProgress: (x) => {
            transfer.progress = x.loaded

            if (x.total && transfer.size !== x.total) {
              transfer.size = x.total
            }
            if (transfer.progress === transfer.size) {
              transfer.status = 'completed'
            } else if (transfer.status !== 'inprogress') {
              transfer.status = 'inprogress'
            }
          },
        })
        .then((res) => {
          const url = window.URL.createObjectURL(new Blob([res.data]))
          const link = document.createElement('a')
          link.href = url
          link.setAttribute('download', item.name)
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link)

          transfer.progress = transfer.size
          transfer.status = 'completed'
        })
        .catch((error) => {
          this.$log.error(error)

          transfer.status = 'failed'
          transfer.error = error.message
        })

      this.$accessor.files.addTransfer(transfer)
    }

    upload(dt: DataTransfer) {
      const url = '/file?pwd=' + encodeURIComponent(this.$accessor.password)
      this.uploadAreaDrag = false

      for (const file of dt.files) {
        const abortController = new AbortController()

        const formdata = new FormData()
        formdata.append('files', file, file.name)

        let transfer: FileTransfer = {
          id: Math.round(Math.random() * 10000),
          name: file.name,
          direction: 'upload',
          size: file.size,
          progress: 0,
          status: 'pending',
          abortController: abortController,
        }

        this.$http
          .post(url, formdata, {
            signal: abortController.signal,
            withCredentials: false,
            onUploadProgress: (x: any) => {
              transfer.progress = x.loaded

              if (transfer.size !== x.total) {
                transfer.size = x.total
              }
              if (transfer.progress === transfer.size) {
                transfer.status = 'completed'
              } else if (transfer.status !== 'inprogress') {
                transfer.status = 'inprogress'
              }
            },
          })
          .catch((error) => {
            this.$log.error(error)

            transfer.status = 'failed'
            transfer.error = error.message
          })

        this.$accessor.files.addTransfer(transfer)
      }
    }

    openFileBrowser() {
      const input = document.createElement('input')
      input.type = 'file'
      input.setAttribute('multiple', 'true')
      input.onchange = (e: Event) => {
        if (e === null) return

        const dt = new DataTransfer()
        const target = e.target as HTMLInputElement
        if (target.files === null) return

        for (const f of target.files) {
          dt.items.add(f)
        }

        this.upload(dt)
      }
      input.click()
    }

    removeTransfer(transfer: FileTransfer) {
      if (transfer.status !== 'completed') {
        transfer.abortController?.abort()
      }
      this.$accessor.files.removeTransfer(transfer)
    }

    async deleteFile(item: FileListItem) {
      const { isConfirmed } = await this.$swal({
        title: this.$t('files.delete_title', { name: item.name }) as string,
        text: this.$t('files.delete_confirm', { name: item.name }) as string,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: this.$t('context.confirm.button_yes') as string,
        cancelButtonText: this.$t('context.confirm.button_cancel') as string,
      })
      if (!isConfirmed) {
        return
      }
      const url =
        '/file?pwd=' + encodeURIComponent(this.$accessor.password) + '&filename=' + encodeURIComponent(item.name)
      try {
        await this.$http.delete(url)
        this.$accessor.files.refresh()
      } catch (error: any) {
        this.$log.error(error)
      }
    }

    fileIcon(file: FileListItem) {
      let className = 'file-icon fas '
      // if is directory
      if (file.type === 'dir') {
        className += 'fa-folder'
        return className
      }
      // try to get file extension
      const ext = file.name.split('.').pop()
      if (ext === undefined) {
        className += 'fa-file'
        return className
      }
      // try to find icon
      switch (ext.toLowerCase()) {
        case 'txt':
        case 'md':
          className += 'fa-file-text'
          break
        case 'pdf':
          className += 'fa-file-pdf'
          break
        case 'zip':
        case 'rar':
        case '7z':
        case 'gz':
          className += 'fa-archive'
          break
        case 'aac':
        case 'flac':
        case 'midi':
        case 'mp3':
        case 'ogg':
        case 'wav':
          className += 'fa-music'
          break
        case 'avi':
        case 'mkv':
        case 'mov':
        case 'mpeg':
        case 'mp4':
        case 'webm':
          className += 'fa-film'
          break
        case 'bmp':
        case 'gif':
        case 'jpeg':
        case 'jpg':
        case 'png':
        case 'svg':
        case 'tiff':
        case 'webp':
          className += 'fa-image'
          break
        default:
          className += 'fa-file'
      }
      return className
    }

    fileSize(size: number) {
      if (size < 1024) {
        return size + ' B'
      }
      if (size < 1024 * 1024) {
        return Math.round(size / 1024) + ' KB'
      }
      if (size < 1024 * 1024 * 1024) {
        return Math.round(size / (1024 * 1024)) + ' MB'
      }
      if (size < 1024 * 1024 * 1024 * 1024) {
        return Math.round(size / (1024 * 1024 * 1024)) + ' GB'
      }
      return Math.round(size / (1024 * 1024 * 1024 * 1024)) + ' TB'
    }
  }
</script>
