// client/src/components/resolution.vue
<template>
  <vue-context class="context" ref="context">
    <template v-for="(conf, i) in configurations">
      <li
        :key="i"
        @click="screenSet(conf)"
        :class="[conf.width === width && conf.height === height && conf.rate === rate ? 'active' : '']"
      >
        <i class="fas fa-desktop"></i>
        <span>{{ conf.width }}x{{ conf.height }}</span>
        <small>{{ conf.rate }}</small>
      </li>
    </template>
  </vue-context>
</template>

<style lang="scss" scoped>
  .context {
    background-color: $background-floating;
    background-clip: padding-box;
    border-radius: 0.25rem;
    display: block;
    margin: 0;
    padding: 5px;
    min-width: 150px;
    z-index: 1500;
    position: fixed;
    list-style: none;
    box-sizing: border-box;
    max-height: calc(100% - 50px);
    overflow-y: auto;
    color: $interactive-normal;
    user-select: none;
    box-shadow: $elevation-high;
    scrollbar-width: thin;
    scrollbar-color: $background-secondary transparent;

    &::-webkit-scrollbar {
      width: 8px;
    }

    &::-webkit-scrollbar-track {
      background-color: transparent;
    }

    &::-webkit-scrollbar-thumb {
      background-color: $background-secondary;
      border: 2px solid $background-floating;
      border-radius: 4px;
    }

    &::-webkit-scrollbar-thumb:hover {
      background-color: $background-floating;
    }

    > li {
      margin: 0;
      position: relative;
      align-content: center;
      display: flex;
      flex-direction: row;
      padding: 8px;
      cursor: pointer;
      border-radius: 3px;

      i {
        margin-right: 10px;
      }

      span {
        flex-grow: 1;
      }

      small {
        font-size: 0.7em;
        justify-self: flex-end;
        align-self: flex-end;
      }

      &.active,
      &:hover,
      &:focus {
        text-decoration: none;
        background-color: $background-modifier-hover;
        color: $interactive-hover;
      }

      &:focus {
        outline: 0;
      }
    }

    &:focus {
      outline: 0;
    }
  }
</style>

<script lang="ts">
  import { Component, Ref, Vue } from 'vue-property-decorator'
  import { ScreenResolution } from '~/neko/types'

  // @ts-ignore
  import { VueContext } from 'vue-context'

  @Component({
    name: 'neko-resolution',
    components: {
      'vue-context': VueContext,
    },
  })
  export default class extends Vue {
    @Ref('context') readonly context!: VueContext

    get width() {
      return this.$accessor.video.width
    }

    get height() {
      return this.$accessor.video.height
    }

    get rate() {
      return this.$accessor.video.rate
    }

    get configurations() {
      return this.$accessor.video.configurations
    }

    open(event: MouseEvent) {
      this.context.open(event)
    }

    screenSet(resolution: ScreenResolution) {
      this.$accessor.video.screenSet(resolution)
    }
  }
</script>

// client/src/features/video/Resolution.tsx
import { useStore } from 'zustand'
import { cn } from '@/lib/utils'
import { client } from '@/state/client'
import { a11y } from '@/components/a11y'

const item =
  'relative flex cursor-pointer flex-row rounded-[3px] p-2 hover:bg-background-modifier-hover hover:text-interactive-hover focus:bg-background-modifier-hover focus:text-interactive-hover focus:outline-0'

// the screen sizes the server offers; inside the player (not fixed), so an open side panel does not cover it
export function Resolution({ onPick }: { onPick: () => void }) {
  const { size, configurations } = useStore(client.store, (s) => s.screen)
  const { width, height, rate } = size
  return (
    <ul
      className="absolute z-[1500] block max-h-[calc(100%-50px)] min-w-[150px] overflow-y-auto rounded-[3.5px] bg-background-floating bg-clip-padding p-[5px] text-interactive-normal shadow-elevation-high select-none [scrollbar-color:var(--color-background-secondary)_transparent] [scrollbar-width:thin]"
      role="menu"
      data-testid="resolution-menu"
      style={{ top: 50, right: 50 }}
      onClick={(e) => e.stopPropagation()}
    >
      {configurations.map((c, i) => {
        const active = c.width === width && c.height === height && c.rate === rate
        return (
          <li
            key={i}
            className={cn(item, active && 'bg-background-modifier-hover text-interactive-hover')}
            data-testid="resolution-item"
            data-active={active || undefined}
            {...a11y(`${c.width}x${c.height}@${c.rate}`, 'menuitem')}
            onClick={() => (client.setScreenSize(c.width, c.height, c.rate), onPick())}
          >
            <i className="fas fa-desktop mr-2.5"></i>
            <span className="grow">
              {c.width}x{c.height}
            </span>
            <small className="self-end text-[0.7em]">{c.rate}</small>
          </li>
        )
      })}
    </ul>
  )
}
